### ISSUE TITLE
#update-to-latest `did list` does not work

### ISSUE THREAD

**Issue by mattcollier** [digitalbazaar/did-client#19]
on commit fad5129528d5b7b356597c59ef2debfd910ab733
```
Error: "undefined" ledger not supported
    at _runLedgerCommand (/home/matt/dev/did-cli/did:655:13)
    at Object.handler (/home/matt/dev/did-cli/did:274:13)
    at Object.runCommand (/home/matt/dev/did-cli/node_modules/yargs/lib/command.js:237:40)
    at Object.parseArgs [as _parseArgs] (/home/matt/dev/did-cli/node_modules/yargs/yargs.js:1090:30)
    at Function.get [as argv] (/home/matt/dev/did-cli/node_modules/yargs/yargs.js:1024:21)
    at Object.<anonymous> (/home/matt/dev/did-cli/did:645:7)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)

```

**Comment by dmitrizagidulin** [comment]
Should be fixed in latest, closing.
