### ISSUE TITLE
#update-to-latest `did info` does not work

### ISSUE THREAD

**Issue by mattcollier** [digitalbazaar/did-client#21]
Using fad5129528d5b7b356597c59ef2debfd910ab733
```
./did info did:v1:nym:z6MkpAjEyWmJBWNpfX4bnZSFZGToEK5nxChS3vGQrwvD4kQM -H vop1.digitalbazaar.com
ReferenceError: _getHostnames is not defined
    at api.info (/home/matt/dev/did-cli/lib/drivers/veres/index.js:303:5)
    at _runLedgerCommand (/home/matt/dev/did-cli/did:665:5)
    at Object.handler (/home/matt/dev/did-cli/did:427:13)
    at Object.runCommand (/home/matt/dev/did-cli/node_modules/yargs/lib/command.js:237:40)
    at Object.parseArgs [as _parseArgs] (/home/matt/dev/did-cli/node_modules/yargs/yargs.js:1090:30)
    at Function.get [as argv] (/home/matt/dev/did-cli/node_modules/yargs/yargs.js:1024:21)
    at Object.<anonymous> (/home/matt/dev/did-cli/did:645:7)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
```

**Comment by dmitrizagidulin** [comment]
This should be working in the latest version, closing. (Feel free to reopen if this comes up again.)
