### ISSUE TITLE
npm install failing - code ELIFECYCLE

### ISSUE THREAD

**Issue by ydennisy** [digitalbazaar/did-client#3]
Hello,
I am trying to use `npm` to install the `did-client`.
The build is failing with code `ELIFECYCLE`
I am using node v6.9.4 and npm v4.1.1 on MacOSX.
The full error is shown below:
```
1 error generated.
make: *** [Release/obj.target/urdna2015/lib/native/IdentifierIssuer.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Darwin 17.4.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/dennisy/node_modules/rdf-canonize
gyp ERR! node -v v6.9.4
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
/Users/dennisy
├─┬ jsonld@0.5.21 
│ ├── semver@5.5.0 
│ └── xmldom@0.1.19 
├── lodash@4.17.5 
├── node-forge@0.7.3 
├─┬ program@1.0.0 
│ ├── async@0.2.10 
│ ├─┬ expand-tilde@2.0.2 
│ │ └─┬ homedir-polyfill@1.0.1 
│ │   └── parse-passwd@1.0.0 
│ └── ini@1.1.0 
├─┬ r2@2.0.0 
│ └── node-fetch@2.1.1 
└── universalify@0.1.1 

npm WARN enoent ENOENT: no such file or directory, open '/Users/dennisy/package.json'
npm WARN equihash-signature@0.0.1-3 requires a peer of jsonld@^1.0.1 but none was installed.
npm WARN dennisy No description
npm WARN dennisy No repository field.
npm WARN dennisy No README data
npm WARN dennisy No license field.
npm ERR! Darwin 17.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "did-client"
npm ERR! node v6.9.4
npm ERR! npm  v4.1.1
npm ERR! code ELIFECYCLE

npm ERR! rdf-canonize@0.2.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the rdf-canonize@0.2.3 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the rdf-canonize package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs rdf-canonize
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls rdf-canonize
npm ERR! There is likely additional logging output above.
```
Thanks in advance.

**Comment by davidlehn** [comment]
To work with the live servers you'll need the more recent code from github vs 0.2.0 in npm.  You'll also need node 8.6+.

**Comment by ydennisy** [comment]
@davidlehn thank you seems to work!

**Comment by davidlehn** [comment]
A new version was pushed to npm late yesterday too, in case you wanted to install via that route.
